using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;
using FreshFit.Model.Models;
using Microsoft.EntityFrameworkCore;

namespace FreshFit.DAL.Seed
{
    public class FoodSeed
    {
        public void AddFoodData(ModelBuilder modelBuilder)
        {
            //Ekmekller dilim üzerinden hesaplanmıştır
            modelBuilder.Entity<Food>().HasData(
            
                new Food { ID = 1, Name = "Light Ekmeği", Calory = 48, Carbohydrate = 12.07, Fat = 0.82, Protein = 2.12 ,StringPicture = ".\\resimler\\1.jpg"},
        new Food { ID = 2, Name = "Çavdar Ekmeği", Calory = 65, Carbohydrate = 12.07, Fat = 0.82, Protein = 2.12, StringPicture = ".\\resimler\\2.jpg" },
                new Food { ID = 3, Name = "Tahıllı Ekmek", Calory = 66, Carbohydrate = 10.84, Fat = 1.06, Protein = 3.34, StringPicture = ".\\resimler\\3.jpg" },
                new Food { ID = 4, Name = "Kepekli Ekmek", Calory = 62, Carbohydrate = 11.95, Fat = 0.85, Protein = 2.2, StringPicture = ".\\resimler\\4.jpg" },
                new Food { ID = 5, Name = "Beyaz Ekmek", Calory = 72, Carbohydrate = 13.62, Fat = 1, Protein = 2.55, StringPicture = ".\\resimler\\5.jpg" },
                new Food { ID = 6, Name = "Mısır Ekmeği", Calory = 62, Carbohydrate = 11.45, Fat = 1.31, Protein = 1.08, StringPicture = ".\\resimler\\6.jpg" },
                new Food { ID = 7, Name = "Sandviç Ekmeği (Beyaz)", Calory = 216, Carbohydrate = 40.86, Fat = 3, Protein = 7.65, StringPicture = ".\\resimler\\7.jpg" },
                new Food { ID = 8, Name = "Sandviç Ekmeği (Tahıllı)", Calory = 198, Carbohydrate = 32.52, Fat = 3.18, Protein = 10.02, StringPicture = ".\\resimler\\8.jpg" },
                new Food { ID = 9, Name = "Simit", Calory = 434, Carbohydrate = 69, Fat = 17, Protein = 1, StringPicture = ".\\resimler\\9.jpg" },
                new Food { ID = 10, Name = "Yulaf Gevreği (Musli)", Calory = 141, Carbohydrate = 30.28, Fat = 1.32, Protein = 4.48, StringPicture = ".\\resimler\\10.jpg" },
                new Food { ID = 11, Name = "Sade Mısır Gevreği (Cornﬂakes)", Calory = 101, Carbohydrate = 24.28, Fat = 0.03, Protein = 1.88, StringPicture = ".\\resimler\\11.jpg" },
                new Food { ID = 12, Name = "Tam Tahıllı Gevrek", Calory = 124, Carbohydrate = 27.4, Fat = 1.12, Protein = 2.39, StringPicture = ".\\resimler\\12.jpg" },
                new Food { ID = 13, Name = "Yulaf Ezmesi", Calory = 73, Carbohydrate = 13.4, Fat = 1.26, Protein = 3.2, StringPicture = ".\\resimler\\13.jpg" },
                new Food { ID = 14, Name = "Patates", Calory = 77, Carbohydrate = 17.49, Fat = 0.09, Protein = 2.05, StringPicture = ".\\resimler\\14.jpg" },
                new Food { ID = 15, Name = "İnek Sütü(Tam Yaglı)", Calory = 110, Carbohydrate = 8.64, Fat = 5.85, Protein = 5.67, StringPicture = ".\\resimler\\15.jpg" },
                new Food { ID = 16, Name = "İnek Sütü (Yarım Yaglı)", Calory = 92, Carbohydrate = 10.84, Fat = 2.08, Protein = 6.66, StringPicture = ".\\resimler\\16.jpg" },
                new Food { ID = 17, Name = "İnek Sütü (Yagsız)", Calory = 76, Carbohydrate = 10, Fat = 0.01, Protein = 6.66, StringPicture = ".\\resimler\\17.jpg" },
                new Food { ID = 18, Name = "Keçi Sütü", Calory = 124, Carbohydrate = 10, Fat = 6.66, Protein = 6.66, StringPicture = ".\\resimler\\18.jpg" },
                new Food { ID = 19, Name = "Soya Sütü", Calory = 112, Carbohydrate = 17.6, Fat = 2.4, Protein = 4, StringPicture = ".\\resimler\\19.jpg" },
                new Food { ID = 20, Name = "Hindistan Cevizi Sütü", Calory = 200, Carbohydrate = 7.69, Fat = 18.49, Protein = 1.54, StringPicture = ".\\resimler\\20.jpg" },
                new Food { ID = 21, Name = "Beyaz Peynir(Yarım Yaglı İnek)", Calory = 60, Carbohydrate = 2.44, Fat = 4.58, Protein = 2.35, StringPicture = ".\\resimler\\21.jpg" },
                new Food { ID = 22, Name = "Süzme Peynir", Calory = 69, Carbohydrate = 1.05, Fat = 5.4, Protein = 4.05, StringPicture = ".\\resimler\\22.jpg" },
                new Food { ID = 23, Name = "Lor Peyniri	", Calory = 43, Carbohydrate = 0.92, Fat = 0.21, Protein = 8.6, StringPicture = ".\\resimler\\23.jpg" },
                new Food { ID = 24, Name = "Light Kaşar Peyniri", Calory = 75.3, Carbohydrate = 1.2, Fat = 3.75, Protein = 9.15, StringPicture = ".\\resimler\\24.jpg" },
                new Food { ID = 25, Name = "Labne Peyniri", Calory = 95.5, Carbohydrate = 2.25, Fat = 8.5, Protein = 2.45, StringPicture = ".\\resimler\\25.jpg" },
                new Food { ID = 26, Name = "Örgü Peynir", Calory = 97.2, Carbohydrate = 0.45, Fat = 7.05, Protein = 8, StringPicture = ".\\resimler\\26.jpg" },
                new Food { ID = 27, Name = "Dil Peyniri", Calory = 81, Carbohydrate = 0.6, Fat = 5.7, Protein = 6.78, StringPicture = ".\\resimler\\27.jpg" },
                new Food { ID = 28, Name = "Mozarella", Calory = 90, Carbohydrate = 0.66, Fat = 6.71, Protein = 6.61, StringPicture = ".\\resimler\\28.jpg" },
                new Food { ID = 29, Name = "Hellim Peyniri", Calory = 91.5, Carbohydrate = 0.25, Fat = 6.9, Protein = 7.13, StringPicture = ".\\resimler\\29.jpg" },
                new Food { ID = 30, Name = "Kefir (Yaglı)", Calory = 120, Carbohydrate = 10, Fat = 6, Protein = 5.6, StringPicture = ".\\resimler\\30.jpg" },
                new Food { ID = 31, Name = "Kefir (Yagsız)", Calory = 74, Carbohydrate = 8.06, Fat = 1.67, Protein = 6.82, StringPicture = ".\\resimler\\31.jpg" },
                new Food { ID = 32, Name = "Meyveli Kefir", Calory = 156, Carbohydrate = 20, Fat = 6, Protein = 5.4, StringPicture = ".\\resimler\\32.jpg" },
                new Food { ID = 33, Name = "Süzme Yoğurt", Calory = 95, Carbohydrate = 4.5, Fat = 6.3, Protein = 5.04, StringPicture = ".\\resimler\\33.jpg" },
                new Food { ID = 34, Name = "Yoğurt (Yaglı)", Calory = 87, Carbohydrate = 3.58, Fat = 4.5, Protein = 8.1, StringPicture = ".\\resimler\\34.jpg" },
                new Food { ID = 35, Name = "Yoğurt (Yagsız)", Calory = 53, Carbohydrate = 3.24, Fat = 0.35, Protein = 9.17, StringPicture = ".\\resimler\\35.jpg" },
                new Food { ID = 36, Name = "Meyveli Yoğurt", Calory = 95, Carbohydrate = 11.06, Fat = 2.7, Protein = 6.6, StringPicture = ".\\resimler\\36.jpg" },
                new Food { ID = 37, Name = "Ayran", Calory = 76, Carbohydrate = 5.6, Fat = 4, Protein = 4, StringPicture = ".\\resimler\\37.jpg" },
                new Food { ID = 38, Name = "Cacık", Calory = 115, Carbohydrate = 11, Fat = 4.86, Protein = 6.66, StringPicture = ".\\resimler\\38.jpg" },
                new Food { ID = 39, Name = "Badem Sütü", Calory = 48, Carbohydrate = 6, Fat = 2.2, Protein = 1, StringPicture = ".\\resimler\\39.jpg" },
                new Food { ID = 40, Name = "Elma", Calory = 95, Carbohydrate = 25.13, Fat = 0.31, Protein = 0.47, StringPicture = ".\\resimler\\40.jpg" },
                new Food { ID = 41, Name = "Armut", Calory = 101, Carbohydrate = 27.11, Fat = 0.25, Protein = 0.64, StringPicture = ".\\resimler\\41.jpg" },
                new Food { ID = 42, Name = "Portakal", Calory = 62, Carbohydrate = 15.39, Fat = 0.16, Protein = 1.23, StringPicture = ".\\resimler\\42.jpg" },
                new Food { ID = 43, Name = "Greyfurt", Calory = 74, Carbohydrate = 18.45, Fat = 0.25, Protein = 1.35, StringPicture = ".\\resimler\\43.jpg" },
                new Food { ID = 44, Name = "Ayva", Calory = 57, Carbohydrate = 15.3, Fat = 0.1, Protein = 0.4, StringPicture = ".\\resimler\\44.jpg" },
                new Food { ID = 45, Name = "Mandalina", Calory = 40, Carbohydrate = 10.14, Fat = 0.24, Protein = 0.62, StringPicture = ".\\resimler\\45.jpg" },
                new Food { ID = 46, Name = "Kivi", Calory = 42, Carbohydrate = 10.12, Fat = 0.36, Protein = 0.79, StringPicture = ".\\resimler\\46.jpg" },
                new Food { ID = 47, Name = "Muz", Calory = 105, Carbohydrate = 26.95, Fat = 0.39, Protein = 1.29, StringPicture = ".\\resimler\\47.jpg" },
                new Food { ID = 48, Name = "Kayısı", Calory = 17, Carbohydrate = 3.89, Fat = 0.14, Protein = 0.49, StringPicture = ".\\resimler\\48.jpg" },
                new Food { ID = 49, Name = "Çilek", Calory = 46, Carbohydrate = 11.06, Fat = 0.43, Protein = 0.96, StringPicture = ".\\resimler\\49.jpg" },
                new Food { ID = 50, Name = "Trabzon hurması", Calory = 60, Carbohydrate = 15.96, Fat = 0.17, Protein = 0.48, StringPicture = ".\\resimler\\50.jpg" },
                new Food { ID = 51, Name = "Kiraz", Calory = 87, Carbohydrate = 22.09, Fat = 0.28, Protein = 1.46, StringPicture = ".\\resimler\\51.jpg" },
                new Food { ID = 52, Name = "Vişne", Calory = 52, Carbohydrate = 12.55, Fat = 0.31, Protein = 1.03, StringPicture = ".\\resimler\\52.jpg" },
                new Food { ID = 53, Name = "Kavun", Calory = 54, Carbohydrate = 13.06, Fat = 0.3, Protein = 1.34, StringPicture = ".\\resimler\\53.jpg" },
                new Food { ID = 54, Name = "Karpuz", Calory = 46, Carbohydrate = 11.63, Fat = 0.23, Protein = 0.94, StringPicture = ".\\resimler\\54.jpg" },
                new Food { ID = 55, Name = "Ananas", Calory = 28, Carbohydrate = 7.35, Fat = 0.07, Protein = 0.3, StringPicture = ".\\resimler\\55.jpg" },
                new Food { ID = 56, Name = "Avakado", Calory = 106, Carbohydrate = 5.63, Fat = 9.68, Protein = 1.32, StringPicture = ".\\resimler\\56.jpg" },
                new Food { ID = 57, Name = "Mango", Calory = 99, Carbohydrate = 24.72, Fat = 0.63, Protein = 1.35, StringPicture = ".\\resimler\\57.jpg" },
                new Food { ID = 58, Name = "Ahududu", Calory = 64, Carbohydrate = 14.69, Fat = 0.8, Protein = 1.48, StringPicture = ".\\resimler\\58.jpg" },
                new Food { ID = 59, Name = "Böğürtlen", Calory = 62, Carbohydrate = 13.84, Fat = 0.71, Protein = 2, StringPicture = ".\\resimler\\59.jpg" },
                new Food { ID = 60, Name = "Yaban Mersini", Calory = 84, Carbohydrate = 21.45, Fat = 0.49, Protein = 1.1, StringPicture = ".\\resimler\\60.jpg" },
                new Food { ID = 61, Name = "Yeşil Erik", Calory = 76, Carbohydrate = 18.84, Fat = 0.46, Protein = 1.15, StringPicture = ".\\resimler\\61.jpg" },
                new Food { ID = 62, Name = "Kumkuat", Calory = 13, Carbohydrate = 3.02, Fat = 0.16, Protein = 0.36, StringPicture = ".\\resimler\\62.jpg" },
                new Food { ID = 63, Name = "Kırmızı Erik", Calory = 81, Carbohydrate = 21.01, Fat = 0.31, Protein = 0.97, StringPicture = ".\\resimler\\63.jpg" },
                new Food { ID = 64, Name = "Yenidüny", Calory = 70, Carbohydrate = 18.09, Fat = 0.3, Protein = 0.64, StringPicture = ".\\resimler\\64.jpg" },
                new Food { ID = 65, Name = "İncir", Calory = 37, Carbohydrate = 9.59, Fat = 0.15, Protein = 0.38, StringPicture = ".\\resimler\\65.jpg" },
                new Food { ID = 66, Name = "Dut", Calory = 60, Carbohydrate = 13.72, Fat = 0.55, Protein = 2.02, StringPicture = ".\\resimler\\66.jpg" },
                new Food { ID = 67, Name = "Üzüm", Calory = 104, Carbohydrate = 27.33, Fat = 0.24, Protein = 1.09, StringPicture = ".\\resimler\\67.jpg" },
                new Food { ID = 68, Name = "Nar", Calory = 72, Carbohydrate = 16.27, Fat = 1.02, Protein = 1.45, StringPicture = ".\\resimler\\68.jpg" },
                new Food { ID = 69, Name = "Şeftali", Calory = 58, Carbohydrate = 14.31, Fat = 0.38, Protein = 1.36, StringPicture = ".\\resimler\\69.jpg" },
                new Food { ID = 70, Name = "Limon", Calory = 17, Carbohydrate = 5.41, Fat = 0.17, Protein = 0.64, StringPicture = ".\\resimler\\70.jpg" },
                new Food { ID = 71, Name = "Kuru İncir", Calory = 47, Carbohydrate = 12.14, Fat = 0.18, Protein = 0.63, StringPicture = ".\\resimler\\71.jpg" },
                new Food { ID = 72, Name = "Kuru üzüm", Calory = 89.7, Carbohydrate = 23.75, Fat = 14, Protein = 0.92, StringPicture = ".\\resimler\\72.jpg" },
                new Food { ID = 73, Name = "Kuru kayısı", Calory = 16, Carbohydrate = 4.38, Fat = 0.04, Protein = 0.24, StringPicture = ".\\resimler\\73.jpg" },
                new Food { ID = 74, Name = "Kuru mürdüm eriği", Calory = 20, Carbohydrate = 5.37, Fat = 0.03, Protein = 0.18, StringPicture = ".\\resimler\\74.jpg" },
                new Food { ID = 75, Name = "Kuru yaban mersini", Calory = 91, Carbohydrate = 24.13, Fat = 0.4, Protein = 0.12, StringPicture = ".\\resimler\\75.jpg" },
                new Food { ID = 76, Name = "Hurma", Calory = 23, Carbohydrate = 6.23, Fat = 0.03, Protein = 0.2, StringPicture = ".\\resimler\\76.jpg" },
                new Food { ID = 77, Name = "Kuru dut	", Calory = 67.6, Carbohydrate = 16.98, Fat = 0.36, Protein = 0.88, StringPicture = ".\\resimler\\77.jpg" },
                new Food { ID = 78, Name = "Taze Sıkılmış Meyve Suyu	", Calory = 124, Carbohydrate = 29.5, Fat = 0, Protein = 0.44, StringPicture = ".\\resimler\\78.jpg" },
                new Food { ID = 79, Name = "Domates	", Calory = 22, Carbohydrate = 4.78, Fat = 0.25, Protein = 1.08, StringPicture = ".\\resimler\\79.jpg" },
                new Food { ID = 80, Name = "Çeri Domates	", Calory = 27, Carbohydrate = 5.8, Fat = 0.3, Protein = 1.31, StringPicture = ".\\resimler\\80.jpg" },
                new Food { ID = 81, Name = "Salatalık", Calory = 15, Carbohydrate = 3.63, Fat = 0.11, Protein = 0.65, StringPicture = ".\\resimler\\81.jpg" },
                new Food { ID = 82, Name = "Marul Kıvırcık", Calory = 5, Carbohydrate = 1.03, Fat = 0.05, Protein = 0.49, StringPicture = ".\\resimler\\82.jpg" },
                new Food { ID = 83, Name = "Çarliston Biber", Calory = 12, Carbohydrate = 2.46, Fat = 0.21, Protein = 0.76, StringPicture = ".\\resimler\\83.jpg" },
                new Food { ID = 84, Name = "Kırmızı Biber", Calory = 37, Carbohydrate = 7.18, Fat = 0.36, Protein = 1.18, StringPicture = ".\\resimler\\84.jpg" },
                new Food { ID = 85, Name = "Nane", Calory = 1, Carbohydrate = 0.24, Fat = 0.01, Protein = 0.06, StringPicture = ".\\resimler\\85.jpg" },
                new Food { ID = 86, Name = "Reyhan/Fesleğen", Calory = 1, Carbohydrate = 0.23, Fat = 0.03, Protein = 0.13, StringPicture = ".\\resimler\\86.jpg" },
                new Food { ID = 87, Name = "Dereotu", Calory = 1, Carbohydrate = 0.23, Fat = 0.03, Protein = 0.13, StringPicture = ".\\resimler\\87.jpg" },
                new Food { ID = 88, Name = "Kişniş", Calory = 5, Carbohydrate = 0.99, Fat = 0.32, Protein = 0.22, StringPicture = ".\\resimler\\88.jpg" },
                new Food { ID = 89, Name = "Biberiye", Calory = 4, Carbohydrate = 0.77, Fat = 0.18, Protein = 0.06, StringPicture = ".\\resimler\\89.jpg" },
                new Food { ID = 90, Name = "Maydanoz", Calory = 1, Carbohydrate = 0.24, Fat = 0.03, Protein = 0.11, StringPicture = ".\\resimler\\90.jpg" },
                new Food { ID = 91, Name = "Turp", Calory = 19, Carbohydrate = 3.94, Fat = 0.12, Protein = 0.79, StringPicture = ".\\resimler\\91.jpg" },
                new Food { ID = 92, Name = "Roka", Calory = 5, Carbohydrate = 0.73, Fat = 0.13, Protein = 0.52, StringPicture = ".\\resimler\\92.jpg" },
                new Food { ID = 93, Name = "Kereviz Yaprağı", Calory = 16, Carbohydrate = 3, Fat = 0.17, Protein = 0.7, StringPicture = ".\\resimler\\93.jpg" },
                new Food { ID = 94, Name = "Karnabahar", Calory = 27, Carbohydrate = 5.32, Fat = 0.3, Protein = 2.05, StringPicture = ".\\resimler\\94.jpg" },
                new Food { ID = 95, Name = "Brokoli", Calory = 31, Carbohydrate = 6.04, Fat = 0.34, Protein = 2.57, StringPicture = ".\\resimler\\95.jpg" },
                new Food { ID = 96, Name = "Brüksel Lahanası", Calory = 38, Carbohydrate = 7.88, Fat = 0.26, Protein = 2.97, StringPicture = ".\\resimler\\96.jpg" },
                new Food { ID = 97, Name = "Beyaz Lahana", Calory = 22, Carbohydrate = 5.16, Fat = 0.09, Protein = 1.14, StringPicture = ".\\resimler\\97.jpg" },
                new Food { ID = 98, Name = "Kırmızı Lahana", Calory = 28, Carbohydrate = 6.56, Fat = 0.14, Protein = 1.27, StringPicture = ".\\resimler\\98.jpg" },
                new Food { ID = 99, Name = "Havuç", Calory = 25, Carbohydrate = 5.84, Fat = 0.15, Protein = 0.57, StringPicture = ".\\resimler\\99.jpg" },
                new Food { ID = 100, Name = "Sarımsak", Calory = 4, Carbohydrate = 0.99, Fat = 0.02, Protein = 0.19, StringPicture = ".\\resimler\\100.jpg" },
                new Food { ID = 101, Name = "Soğan", Calory = 44, Carbohydrate = 10.27, Fat = 0.11, Protein = 1.21, StringPicture = ".\\resimler\\101.jpg" },
                new Food { ID = 102, Name = "Yeşil Soğan", Calory = 2, Carbohydrate = 0.44, Fat = 0.01, Protein = 0.11, StringPicture = ".\\resimler\\102.jpg" },
                new Food { ID = 103, Name = "Semizotu", Calory = 9, Carbohydrate = 1.46, Fat = 0.15, Protein = 0.87, StringPicture = ".\\resimler\\103.jpg" },
                new Food { ID = 104, Name = "Pazı", Calory = 7, Carbohydrate = 1.35, Fat = 0.07, Protein = 0.65, StringPicture = ".\\resimler\\104.jpg" },
                new Food { ID = 105, Name = "Kabak", Calory = 33, Carbohydrate = 6.1, Fat = 0.63, Protein = 2.37, StringPicture = ".\\resimler\\105.jpg" },
                new Food { ID = 106, Name = "Kestane (Haşlama veya Izgara)", Calory = 98, Carbohydrate = 22.09, Fat = 0.62, Protein = 0.81, StringPicture = ".\\resimler\\106.jpg" },
                new Food { ID = 107, Name = "Patlamış Mısır (Yagsız/Tuzsuz)", Calory = 76, Carbohydrate = 15.58, Fat = 0.84, Protein = 2.4, StringPicture = ".\\resimler\\107.jpg" },
                new Food { ID = 108, Name = "Sarı Leblebi", Calory = 71, Carbohydrate = 11.7, Fat = 1.25, Protein = 3.73, StringPicture = ".\\resimler\\108.jpg" },
                new Food { ID = 109, Name = "Beyaz Leblebi", Calory = 72, Carbohydrate = 11.9, Fat = 1.2, Protein = 3.79, StringPicture = ".\\resimler\\109.jpg" },
                new Food { ID = 110, Name = "Fındık", Calory = 97, Carbohydrate = 2.57, Fat = 9.36, Protein = 2.3, StringPicture = ".\\resimler\\110.jpg" },
                new Food { ID = 111, Name = "Badem", Calory = 97, Carbohydrate = 3.62, Fat = 8.39, Protein = 3.55, StringPicture = ".\\resimler\\111.jpg" },
                new Food { ID = 112, Name = "Ceviz", Calory = 52, Carbohydrate = 1.1, Fat = 5.22, Protein = 1.22, StringPicture = ".\\resimler\\112.jpg" },
                new Food { ID = 113, Name = "Kabak Çekirdeği", Calory = 104.4, Carbohydrate = 2.68, Fat = 8.42, Protein = 6.6, StringPicture = ".\\resimler\\113.jpg" },
                new Food { ID = 114, Name = "Çiğ Kaju", Calory = 111, Carbohydrate = 6.04, Fat = 8.77, Protein = 3.64, StringPicture = ".\\resimler\\114.jpg" },
                new Food { ID = 115, Name = "Galeta", Calory = 32, Carbohydrate = 5.2, Fat = 0.76, Protein = 0.66, StringPicture = ".\\resimler\\115.jpg" },
                new Food { ID = 116, Name = "Grissini", Calory = 22, Carbohydrate = 3.8, Fat = 0.48, Protein = 0.52, StringPicture = ".\\resimler\\116.jpg" },
                new Food { ID = 117, Name = "Grissini(ince)", Calory = 22, Carbohydrate = 3.8, Fat = 0.48, Protein = 0.52, StringPicture = ".\\resimler\\117.jpg" },
                new Food { ID = 118, Name = "Köfte", Calory = 59, Carbohydrate = 2.4, Fat = 2.7, Protein = 6.3, StringPicture = ".\\resimler\\118.jpg" },
                new Food { ID = 119, Name = "Biftek", Calory = 75.6, Carbohydrate = 0, Fat = 4.5, Protein = 8.2, StringPicture = ".\\resimler\\119.jpg" },
                new Food { ID = 120, Name = "Dana Antrikot", Calory = 82, Carbohydrate = 0, Fat = 4.10, Protein = 10.73, StringPicture = ".\\resimler\\120.jpg" },
                new Food { ID = 121, Name = "Dana Kuşbaşı", Calory = 65.1, Carbohydrate = 0, Fat = 3.7, Protein = 7.44, StringPicture = ".\\resimler\\121.jpg" },
                new Food { ID = 122, Name = "Yagsız Koyun Eti", Calory = 70, Carbohydrate = 0.02, Fat = 3.33, Protein = 10.03, StringPicture = ".\\resimler\\122.jpg" },
                new Food { ID = 123, Name = "Tavşan", Calory = 68, Carbohydrate = 0, Fat = 2.77, Protein = 10.03, StringPicture = ".\\resimler\\123.jpg" },
                new Food { ID = 124, Name = "Hindi (Göğüs)", Calory = 63, Carbohydrate = 0, Fat = 1.73, Protein = 11.08, StringPicture = ".\\resimler\\124.jpg" },
                new Food { ID = 125, Name = "Hindi (But)", Calory = 62, Carbohydrate = 0, Fat = 2.95, Protein = 8.36, StringPicture = ".\\resimler\\125.jpg" },
                new Food { ID = 126, Name = "Tavuk (Göğüs)", Calory = 76, Carbohydrate = 0, Fat = 1.58, Protein = 15.27, StringPicture = ".\\resimler\\126.jpg" },
                new Food { ID = 127, Name = "Tavuk (But)", Calory = 66, Carbohydrate = 0, Fat = 3.88, Protein = 7.25, StringPicture = ".\\resimler\\127.jpg" },
                new Food { ID = 128, Name = "Tavuk (Kanat)", Calory = 61, Carbohydrate = 0, Fat = 2.44, Protein = 9.14, StringPicture = ".\\resimler\\128.jpg" },
                new Food { ID = 129, Name = "Yumurta (Haşlanmış)", Calory = 70, Carbohydrate = 0.5, Fat = 4.77, Protein = 5.66, StringPicture = ".\\resimler\\129.jpg" },
                new Food { ID = 130, Name = "Somon", Calory = 76, Carbohydrate = 0, Fat = 2.64, Protein = 12.29, StringPicture = ".\\resimler\\130.jpg" },
                new Food { ID = 131, Name = "Somon (Füme)", Calory = 103, Carbohydrate = 0, Fat = 3.63, Protein = 17.59, StringPicture = ".\\resimler\\131.jpg" },
                new Food { ID = 132, Name = "Light Ton Balığı", Calory = 86, Carbohydrate = 0, Fat = 0.96, Protein = 19.44, StringPicture = ".\\resimler\\132.jpg" },
                new Food { ID = 133, Name = "Alabalık", Calory = 119, Carbohydrate = 0, Fat = 5.24, Protein = 16.9, StringPicture = ".\\resimler\\133.jpg" },
                new Food { ID = 134, Name = "Istakoz", Calory = 129, Carbohydrate = 0, Fat = 1.25, Protein = 27.55, StringPicture = ".\\resimler\\134.jpg" },
                new Food { ID = 135, Name = "Levrek", Calory = 125, Carbohydrate = 0, Fat = 2.59, Protein = 23.87, StringPicture = ".\\resimler\\135.jpg" },
                new Food { ID = 136, Name = "Çupra", Calory = 120, Carbohydrate = 0, Fat = 3, Protein = 21.71, StringPicture = ".\\resimler\\136.jpg" },
                new Food { ID = 137, Name = "Karides", Calory = 128, Carbohydrate = 0, Fat = 1.74, Protein = 26.14, StringPicture = ".\\resimler\\137.jpg" },
                new Food { ID = 138, Name = "Sazan", Calory = 138, Carbohydrate = 0, Fat = 6.09, Protein = 19.43, StringPicture = ".\\resimler\\138.jpg" },
                new Food { ID = 139, Name = "Mezgit	", Calory = 99, Carbohydrate = 0, Fat = 1.44, Protein = 19.96, StringPicture = ".\\resimler\\139.jpg" },
                new Food { ID = 140, Name = "İstavrit	", Calory = 156, Carbohydrate = 0, Fat = 5.34, Protein = 25.42, StringPicture = ".\\resimler\\140.jpg" },
                new Food { ID = 141, Name = "Hamsi	", Calory = 42, Carbohydrate = 0, Fat = 1.94, Protein = 5.78, StringPicture = ".\\resimler\\141.jpg" },
                new Food { ID = 142, Name = "Palamut", Calory = 231, Carbohydrate = 0, Fat = 15.67, Protein = 20.99, StringPicture = ".\\resimler\\142.jpg" },
                new Food { ID = 143, Name = "Barbun", Calory = 128, Carbohydrate = 0, Fat = 4.13, Protein = 21.09, StringPicture = ".\\resimler\\143.jpg" },
                new Food { ID = 144, Name = "Kalkan", Calory = 104, Carbohydrate = 0, Fat = 3.21, Protein = 17.49, StringPicture = ".\\resimler\\144.jpg" },
                new Food { ID = 145, Name = "Fener", Calory = 82, Carbohydrate = 0, Fat = 1.66, Protein = 15.78, StringPicture = ".\\resimler\\145.jpg" },
                new Food { ID = 146, Name = "Ahtapot", Calory = 139, Carbohydrate = 0, Fat = 1.77, Protein = 25.35, StringPicture = ".\\resimler\\146.jpg" },
                new Food { ID = 147, Name = "Dil Balığı", Calory = 73, Carbohydrate = 0, Fat = 2.01, Protein = 12.95, StringPicture = ".\\resimler\\147.jpg" },
                new Food { ID = 148, Name = "Mercimek Çorbası", Calory = 99, Carbohydrate = 9.63, Fat = 5.2, Protein = 3.61, StringPicture = ".\\resimler\\148.jpg" },
                new Food { ID = 149, Name = "Tavuk Çorbası", Calory = 56, Carbohydrate = 7, Fat = 1.83, Protein = 3.02, StringPicture = ".\\resimler\\149.jpg" },
                new Food { ID = 150, Name = "Tarhana Çorbası", Calory = 147.6, Carbohydrate = 26.5, Fat = 2.52, Protein = 4.41, StringPicture = ".\\resimler\\150.jpg" },
                new Food { ID = 151, Name = "Sebze Çorbası", Calory = 59, Carbohydrate = 10.91, Fat = 0.81, Protein = 1.98, StringPicture = ".\\resimler\\151.jpg" },
                new Food { ID = 152, Name = "Ezogelin Çorbası", Calory = 93.6, Carbohydrate = 16.83, Fat = 0.3, Protein = 6.21, StringPicture = ".\\resimler\\152.jpg" },
                new Food { ID = 153, Name = "Yayla Çorbası", Calory = 117, Carbohydrate = 9.43, Fat = 7.38, Protein = 3.29, StringPicture = ".\\resimler\\153.jpg" },
                new Food { ID = 154, Name = "Balkabağı Çorbası", Calory = 53, Carbohydrate = 8.1, Fat = 1.83, Protein = 1.85, StringPicture = ".\\resimler\\154.jpg" },
                new Food { ID = 155, Name = "Mantar çorbası", Calory = 123, Carbohydrate = 10.32, Fat = 7.15, Protein = 4.4, StringPicture = ".\\resimler\\155.jpg" },
                new Food { ID = 156, Name = "Brokoli Çorbası", Calory = 156, Carbohydrate = 13.6, Fat = 9.03, Protein = 6.19, StringPicture = ".\\resimler\\156.jpg" },
                new Food { ID = 157, Name = "Lahana Çorbası", Calory = 53, Carbohydrate = 5.65, Fat = 2.39, Protein = 2.88, StringPicture = ".\\resimler\\157.jpg" },
                new Food { ID = 158, Name = "Domates Çorbası", Calory = 68, Carbohydrate = 12.91, Fat = 1.1, Protein = 1.67, StringPicture = ".\\resimler\\158.jpg" },
                new Food { ID = 159, Name = "Sade Salata(karışık yeşillik)", Calory = 9, Carbohydrate = 1.76, Fat = 0.13, Protein = 0.84, StringPicture = ".\\resimler\\159.jpg" },
                new Food { ID = 160, Name = "Mercimekli Lor Peynirli Salata", Calory = 180, Carbohydrate = 28, Fat = 5.1, Protein = 2.7, StringPicture = ".\\resimler\\160.jpg" },
                new Food { ID = 161, Name = "Tavuklu Salata", Calory = 225, Carbohydrate = 5.28, Fat = 8.29, Protein = 31.38, StringPicture = ".\\resimler\\161.jpg" },
                new Food { ID = 162, Name = "Etli Salata", Calory = 267, Carbohydrate = 5.28, Fat = 16.49, Protein = 24.84, StringPicture = ".\\resimler\\162.jpg" },
                new Food { ID = 163, Name = "Ton Balıklı Salata", Calory = 215, Carbohydrate = 5.28, Fat = 6.35, Protein = 21.96, StringPicture = ".\\resimler\\163.jpg" },
                new Food { ID = 164, Name = "Kısır	", Calory = 108, Carbohydrate = 15.84, Fat = 4.64, Protein = 2.71, StringPicture = ".\\resimler\\164.jpg" },
                new Food { ID = 165, Name = "Mercimek Köftesi", Calory = 70, Carbohydrate = 9.95, Fat = 2.41, Protein = 2.75, StringPicture = ".\\resimler\\165.jpg" },
                new Food { ID = 166, Name = "Tabule Salatası", Calory = 588, Carbohydrate = 51, Fat = 33.3, Protein = 14.4, StringPicture = ".\\resimler\\166.jpg" },
                new Food { ID = 167, Name = "Lor Peynirli Yumurtalı Salata	", Calory = 225, Carbohydrate = 6.7, Fat = 9.81, Protein = 16.78, StringPicture = ".\\resimler\\167.jpg" },
                new Food { ID = 168, Name = "Ispanak Yemeği (Pirinçli veya Bulgurlu)", Calory = 115, Carbohydrate = 5.09, Fat = 10.3, Protein = 2.11, StringPicture = ".\\resimler\\168.jpg" },
                new Food { ID = 169, Name = "Ispanak Yemeği (Etli,Kıymalı,Yumurtalı)", Calory = 144.5, Carbohydrate = 6.29, Fat = 11.65, Protein = 5.26, StringPicture = ".\\resimler\\169.jpg" },
                new Food { ID = 170, Name = "ZeytinYaglı Semizotu (Pirinçli veya Bulgurlu)", Calory = 112, Carbohydrate = 4.98, Fat = 10.26, Protein = 1.29, StringPicture = ".\\resimler\\170.jpg" },
                new Food { ID = 171, Name = "Semizotu Yemeği (Etli veya Kıymalı)", Calory = 141.5, Carbohydrate = 6.18, Fat = 11.00, Protein = 4.44, StringPicture = ".\\resimler\\171.jpg" },
                new Food { ID = 172, Name = "ZeytinYaglı Pazı (Pirinçli veya Bulgurlu)", Calory = 131, Carbohydrate = 11.89, Fat = 7.18, Protein = 3.74, StringPicture = ".\\resimler\\172.jpg" },
                new Food { ID = 173, Name = "Pazı Yemeği (Etli veya Kıymalı)", Calory = 160, Carbohydrate = 13.09, Fat = 8.53, Protein = 6.89, StringPicture = ".\\resimler\\173.jpg" },
                new Food { ID = 174, Name = "ZeytinYaglı Taze Fasülye", Calory = 151, Carbohydrate = 21.39, Fat = 5.15, Protein = 5.54 ,StringPicture = ".\\resimler\\174.jpg"},
                new Food { ID = 175, Name = "Taze Fasulye Yemeği (Etli veya Kıymalı)", Calory = 180.5, Carbohydrate = 22.59, Fat = 6.5, Protein = 8.69 ,StringPicture = ".\\resimler\\175.jpg"},
                new Food { ID = 176, Name = "ZeytinYaglı Pırasa(Pirinçli ya da Nohutlu)", Calory = 120, Carbohydrate = 7.25, Fat = 10.27, Protein = 0.91, StringPicture = ".\\resimler\\176.jpg" },
                new Food { ID = 177, Name = "Bezelye Yemeği (Havuçlu)", Calory = 147, Carbohydrate = 11.07, Fat = 10.38, Protein = 3.48 ,StringPicture = ".\\resimler\\177.jpg"},
                new Food { ID = 178, Name = "Bezelye Yemeği (Etli/Tavuklu/Kıymalı)", Calory = 176.5, Carbohydrate = 12.27, Fat = 11.73, Protein = 6.63 ,StringPicture = "\\resimler.\\178.jpg"},
                new Food { ID = 179, Name = "ZeytinYaglı Brokoli", Calory = 80, Carbohydrate = 7.14, Fat = 5.41, Protein = 2.37,StringPicture = ".\\resimler\\179.jpg" },
                new Food { ID = 180, Name = "Brokoli Yemeği (Etli/Kıymalı)", Calory = 110, Carbohydrate = 8.34, Fat = 6.76, Protein = 5.52 ,StringPicture = ".\\resimler\\180.jpg"},
                new Food { ID = 181, Name = "Karnabahar Yemeği", Calory = 115, Carbohydrate = 5.29, Fat = 10.41, Protein = 1.48 ,StringPicture = ".\\resimler\\181.jpg"},
                new Food { ID = 182, Name = "Karnabahar Yemeği (Etli/Tavuklu/Kıymalı)", Calory = 144.5, Carbohydrate = 6.45, Fat = 11.76, Protein = 4.63 ,StringPicture = ".\\resimler\\182.jpg"},
                new Food { ID = 183, Name = "Bamya Yemeği", Calory = 113, Carbohydrate = 4.68, Fat = 10.57, Protein = 1.06 ,StringPicture = ".\\resimler\\183.jpg"},
                new Food { ID = 184, Name = "Bamya Yemeği (Etli/Kıymalı)", Calory = 142.5, Carbohydrate = 5.88, Fat = 11.92, Protein = 4.21 ,StringPicture = ".\\resimler\\184.jpg"},
                new Food { ID = 185, Name = "ZeytinYaglı Türlü", Calory = 112, Carbohydrate = 8.68, Fat = 8.87, Protein = 1.33 ,StringPicture = ".\\resimler\\185.jpg"},
                new Food { ID = 186, Name = "Etli Türlü Yemeği", Calory = 141.5, Carbohydrate = 9.88, Fat = 10.22, Protein = 4.48 ,StringPicture = ".\\resimler\\186.jpg"},
                new Food { ID = 187, Name = "ZeytinYaglı Bakla", Calory = 145, Carbohydrate = 9.76, Fat = 10.69, Protein = 3.32 ,StringPicture = ".\\resimler\\187.jpg"},
                new Food { ID = 188, Name = "ZeytinYaglı Kereviz", Calory = 90, Carbohydrate = 7.14, Fat = 6.37, Protein = 1.92 ,StringPicture = ".\\resimler\\188.jpg"},
                new Food { ID = 189, Name = "ZeytinYaglı Enginar", Calory = 146, Carbohydrate = 12.09, Fat = 10.71, Protein = 2.93, StringPicture = ".\\resimler\\189.jpg" },
                new Food { ID = 190, Name = "Mantar sote (Etli/Tavuklu)	", Calory = 118, Carbohydrate = 5.95, Fat = 10.42, Protein = 1.67 ,StringPicture = ".\\resimler\\190.jpg"},
                new Food { ID = 191, Name = "Sebze Sote (Havuç,Yeşil kabak,brokoli)", Calory = 90, Carbohydrate = 4.55, Fat = 10.19, Protein = 0.94 ,StringPicture = ".\\resimler\\191.jpg"},
                new Food { ID = 192, Name = "ZeytinYaglı Sebze Dolması", Calory = 258, Carbohydrate = 13.59, Fat = 13.59, Protein = 5.6 ,StringPicture = ".\\resimler\\192.jpg"},
                new Food { ID = 193, Name = "ZeytinYaglı yaprak Sarma", Calory = 108, Carbohydrate = 8.32, Fat = 8.15, Protein = 1.33 ,StringPicture = ".\\resimler\\193.jpg"},
                new Food { ID = 194, Name = "Etli Sebze Dolması", Calory = 358, Carbohydrate = 8.3, Fat = 28.17, Protein = 18.67 ,StringPicture = ".\\resimler\\194.jpg"},
                new Food { ID = 195, Name = "Etli Yaprak Sarma", Calory = 176, Carbohydrate = 11.24, Fat = 12.32, Protein = 6.23,StringPicture = ".\\resimler\\195.jpg" },
                new Food { ID = 196, Name = "ZeytinYaglı Kabak", Calory = 111, Carbohydrate = 5.19, Fat = 10.18, Protein = 0.81 ,StringPicture = ".\\resimler\\196.jpg"},
                new Food { ID = 197, Name = "Kabak Yemeği(Etli/Kıymalı)", Calory = 140.5, Carbohydrate = 6.39, Fat = 11.53, Protein = 3.96,StringPicture = ".\\resimler\\197.jpg" },
                new Food { ID = 198, Name = "Yeşil Kabak", Calory = 15, Carbohydrate = 2.69, Fat = 0.36, Protein = 1.14 ,StringPicture = ".\\resimler\\198.jpg"},
                new Food { ID = 199, Name = "Ispanak", Calory = 7, Carbohydrate = 1.09, Fat = 0.12, Protein = 0.86,StringPicture = ".\\resimler\\199.jpg" },
                new Food { ID = 200, Name = "Semizotu", Calory = 7, Carbohydrate = 1.47, Fat = 0.04, Protein = 0.56 ,StringPicture = ".\\resimler\\200.jpg"},
                new Food { ID = 201, Name = "Pazı", Calory = 39, Carbohydrate = 7.89, Fat = 0.28, Protein = 3.7 ,StringPicture = ".\\resimler\\201.jpg"},
                new Food { ID = 202, Name = "Karnabahar", Calory = 29, Carbohydrate = 5.1, Fat = 0.56, Protein = 2.28 ,StringPicture = ".\\resimler\\202.jpg"},
                new Food { ID = 203, Name = "Brokoli", Calory = 55, Carbohydrate = 11.2, Fat = 0.64, Protein = 3.71,StringPicture = ".\\resimler\\203.jpg" },
                new Food { ID = 204, Name = "Brüksel Lahanası", Calory = 56, Carbohydrate = 11.08, Fat = 0.78, Protein = 3.98,StringPicture = ".\\resimler\\204.jpg" },
                new Food { ID = 205, Name = "Taze Fasülye", Calory = 44, Carbohydrate = 9.85, Fat = 0.35, Protein = 2.36 ,StringPicture = ".\\resimler\\205.jpg"},
                new Food { ID = 206, Name = "Havuç", Calory = 55, Carbohydrate = 12.82, Fat = 0.28, Protein = 1.19 ,StringPicture = ".\\resimler\\206.jpg"},
                new Food { ID = 207, Name = "Peynirli omlet", Calory = 254, Carbohydrate = 2.05, Fat = 14.9, Protein = 15.37,StringPicture = ".\\resimler\\207.jpg" },
                new Food { ID = 208, Name = "Mantarlı omlet", Calory = 205, Carbohydrate = 3.69, Fat = 9.9, Protein = 12.46,StringPicture = ".\\resimler\\208.jpg" },
                new Food { ID = 209, Name = "Menemen	", Calory = 205, Carbohydrate = 3.69, Fat = 9.9, Protein = 12.46,StringPicture = ".\\resimler\\209.jpg" },
                new Food { ID = 210, Name = "Kaşarlı omlet", Calory = 260.3, Carbohydrate = 2.2, Fat = 13.29, Protein = 20.27,StringPicture = ".\\resimler\\210.jpg" },
                new Food { ID = 211, Name = "Sebzeli omlet", Calory = 205, Carbohydrate = 3.69, Fat = 9.9, Protein = 12.46 ,StringPicture = ".\\resimler\\211.jpg"},
                new Food { ID = 212, Name = "Yulaﬂı omlet", Calory = 258, Carbohydrate = 14.4, Fat = 10.8, Protein = 14.52 ,StringPicture = ".\\resimler\\212.jpg"},
                new Food { ID = 213, Name = "Omlet Sade", Calory = 185, Carbohydrate = 1, Fat = 14.9, Protein = 11.32 ,StringPicture = ".\\resimler\\213.jpg"},
                new Food { ID = 214, Name = "Mercimek Yemeği", Calory = 100.2, Carbohydrate = 8.54, Fat = 6.22, Protein = 3.29 ,StringPicture = ".\\resimler\\214.jpg"},
                new Food { ID = 215, Name = "Mercimek Yemeği(Etli/Kıymalı)", Calory = 160, Carbohydrate = 10.94, Fat = 8.92, Protein = 9.59 ,StringPicture = ".\\resimler\\215.jpg"},
                new Food { ID = 216, Name = "Nohut Yemeği", Calory = 101.4, Carbohydrate = 9.37, Fat = 6.47, Protein = 1.93 ,StringPicture = ".\\resimler\\216.jpg"},
                new Food { ID = 217, Name = "Nohut Yemeği(Etli/Kıymalı)", Calory = 160.4, Carbohydrate = 11.77, Fat = 9.17, Protein = 8.23,StringPicture = ".\\resimler\\217.jpg" },
                new Food { ID = 218, Name = "Kuru Fasülye Yemeği", Calory = 101.4, Carbohydrate = 9.37, Fat = 6.47, Protein = 1.93 ,StringPicture = ".\\resimler\\218.jpg"},
                new Food { ID = 219, Name = "Kuru Fasülye Yemeği (Etli/Kıymalı)", Calory = 160.4, Carbohydrate = 11.77, Fat = 9.17, Protein = 8.23,StringPicture = ".\\resimler\\219.jpg" },
                new Food { ID = 220, Name = "Bulgur Pilavı", Calory = 80, Carbohydrate = 13.43, Fat = 1.57, Protein = 2.2,StringPicture = ".\\resimler\\220.jpg" },
                new Food { ID = 221, Name = "Bulgur Pilavı (Sebzeli)", Calory = 108, Carbohydrate = 18.93, Fat = 2.07, Protein = 3.25, StringPicture = ".\\resimler\\221.jpg" },
                new Food { ID = 222, Name = "Pirinç Pilavı", Calory = 75, Carbohydrate = 12.94, Fat = 1.94, Protein = 1.24 ,StringPicture = ".\\resimler\\222.jpg"},
                new Food { ID = 223, Name = "Pirinç Pilavı(Sebzeli)", Calory = 103, Carbohydrate = 18.44, Fat = 2.44, Protein = 2.29,StringPicture = ".\\resimler\\223.jpg" },
                new Food { ID = 224, Name = "Şehriye Pilavı", Calory = 77.4, Carbohydrate = 14.67, Fat = 1.96, Protein = 0.2 ,StringPicture = ".\\resimler\\224.jpg"},
                new Food { ID = 225, Name = "Makarna (Haşlama ve Yagsız)", Calory = 74.4, Carbohydrate = 15.07, Fat = 0.58, Protein = 2.62,StringPicture = ".\\resimler\\225.jpg" },
                new Food { ID = 226, Name = "Makarna (Kıymalı)", Calory = 133.4, Carbohydrate = 17.47, Fat = 3.28, Protein = 8.92 ,StringPicture = ".\\resimler\\226.jpg"},
                new Food { ID = 227, Name = "Makarna(Peynirli)", Calory = 117.4, Carbohydrate = 15.99, Fat = 0.79, Protein = 11.22 ,StringPicture = ".\\resimler\\227.jpg"},
                new Food { ID = 228, Name = "ZeytinYaglı Barbunya", Calory = 101.4, Carbohydrate = 9.37, Fat = 6.47, Protein = 1.93 ,StringPicture = ".\\resimler\\228.jpg"},
                new Food { ID = 229, Name = "ZeytinYagı", Calory = 45, Carbohydrate = 0, Fat = 5, Protein = 0 ,StringPicture = ".\\resimler\\229.jpg"},
                new Food { ID = 230, Name = "Fındık Yagı", Calory = 45, Carbohydrate = 0, Fat = 5, Protein = 0 ,StringPicture = ".\\resimler\\230.jpg"},
                new Food { ID = 231, Name = "Ceviz Yagı", Calory = 45, Carbohydrate = 0, Fat = 5, Protein = 0 ,StringPicture = ".\\resimler\\231.jpg"},
                new Food { ID = 232, Name = "TereYag", Calory = 36, Carbohydrate = 0, Fat = 4.06, Protein = 0.04,StringPicture = ".\\resimler\\232.jpg" },
                new Food { ID = 233, Name = "Zeytin (Yeşil/Siyah)", Calory = 45, Carbohydrate = 2.48, Fat = 4.23, Protein = 0.33,StringPicture = ".\\resimler\\233.jpg" }
               
                );
        }
    }
}
